module.exports = [
    {   
        name: "The OG",
        tags: ["Pixel Warrior","Sword Fighter"],
        lore: "Warrior evenemploys the hoariest of all sports movie clichés: the training montage (though Warrior's is set to Beethoven's 'Ode to Joy,' not Bill Conti's 'Gonna Fly Now' or Joe Esposito's 'You're The Best').",
        authorShare: 100,
        content: "./Project_Minting/content/bonsai_pixel.png",
        thumb: "./Project_Minting/thumbs/bonsai_pixel.png",
    },
    {   
        name: "Wild Gaze",
        tags: ["Fierce Reveal","Vicious Cessation"],
        lore: "Instead, she used the Sword of Protection to turn into a more powerful being—the warrior She-Ra.",
        authorShare: 100,
        content: "./Project_Minting/content/bonsai_pixel2.png",
        thumb: "./Project_Minting/thumbs/bonsai_pixel2.png",
    },
    {   
        name: "Nightbreaker",
        tags: ["Magical Postmortem","Dragon's Breath"],
        lore: "Because it features a landmark called the 'Titan of Braavos,' a colossal statue of a warrior holding up a sword.",
        authorShare: 100,
        content: "./Project_Minting/content/bonsai_pixel3.png",
        thumb: "./Project_Minting/thumbs/bonsai_pixel3.png",
    },
    {   
        name: "Darkhead",
        tags: ["Baron's Tear","Werewolf's Cloud"],
        lore: "On the other, the viking warrior lets his hair blow in the wind, footloose and carefree, while another holds out a sword while screaming to charge.",
        authorShare: 100,
        content: "./Project_Minting/content/bonsai_pixel4.png",
        thumb: "./Project_Minting/thumbs/bonsai_pixel4.png",
    },
    {   
        name: "Rumble Sorrow",
        tags: ["Naiad's Afterlife","Howling Bulwark"],
        lore: "'I’m going to bestow to you the sword of a great conservative warrior.' Now we can probably expect Ron Paul supporters to take to the comments section with conspiracy theories about Rubio's ties to the Bush family, and perhaps even China.",
        authorShare: 100,
        content: "./Project_Minting/content/bonsai_pixel5.png",
        thumb: "./Project_Minting/thumbs/bonsai_pixel5.png",
    },
    {   
        name: "Embercrest",
        tags: ["Scandalous Mark","Werewolf's Gruesome Code"],
        lore: "The key to raising every soldier into a great warrior is in strengthening training.",
        authorShare: 100,
        content: "./Project_Minting/content/bonsai_pixel6.png",
        thumb: "./Project_Minting/thumbs/bonsai_pixel6.png",
    },
    {   
        name: "Dragonshield",
        tags: ["Lucid Cull","Juggernaught's Pomell","River's Dusk"],
        lore: "The result is a sometimes-contradictory character—a warrior by training and birthright who prefers diplomacy to battle.",
        authorShare: 100,
        content: "./Project_Minting/content/bonsai_pixel7.png",
        thumb: "./Project_Minting/thumbs/bonsai_pixel7.png",
    },
    {   
        name: "Wild Cut",
        tags: ["Hidden Taunt","Hollow Reign", "Holy Recite"],
        lore: "We’re like blind men, without instructions.” More pragmatic teams like General He’s, which came to Jordan a month before the contest to get a feel for the climate, use the Warrior Competition as a training opportunity.",
        authorShare: 100,
        content: "./Project_Minting/content/bonsai_pixel8.png",
        thumb: "./Project_Minting/thumbs/bonsai_pixel8.png",
    }
];